apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: client-service
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-client-service'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: HEAD
        path: guestbook
      destination:
        server: '{{server}}'
        namespace: "default"
